[package]
name = "axum-404-auth-bug"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
axum = "0.2"
tower = "0.4"
tower-http = { version = "0.1", features = ["auth"] }
